# Generated by Django 5.0.3 on 2024-03-29 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(error_messages={'unique': 'Tên đăng nhập đã tồn tại.'}, help_text='Yêu cầu 30 ký tự hoặc ít hơn. Chỉ chứa chữ cái, số và các ký tự @/./+/-/_', max_length=30, unique=True, verbose_name='username')),
                ('is_superuser', models.BooleanField(default=False, help_text='Chỉ định người dùng có tất cả các quyền quản trị hệ thống.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Chỉ định người dùng có quyền truy cập vào trang quản trị (admin).', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ định người dùng được coi là "active". Hủy chọn để vô hiệu hóa tài khoản này.', verbose_name='active')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Lần đăng nhập cuối')),
                ('name', models.CharField(max_length=30, verbose_name='Tên')),
                ('age', models.IntegerField(verbose_name='Tuổi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phim')),
                ('title', models.CharField(max_length=100, verbose_name='Tên phim')),
                ('genre', models.CharField(max_length=100, verbose_name='Thể loại')),
                ('duration', models.IntegerField(verbose_name='Thời lượng')),
                ('director', models.CharField(max_length=100, verbose_name='Đạo diễn')),
                ('release_date', models.DateField(verbose_name='Ngày công chiếu')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('poster', models.ImageField(upload_to='movie_poster/', verbose_name='Ảnh bìa')),
            ],
            options={
                'verbose_name': 'Phim',
                'verbose_name_plural': 'Phim',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã phòng')),
                ('name', models.CharField(help_text='VD: A, B, C...', max_length=100, verbose_name='Tên phòng')),
                ('capacity', models.IntegerField(verbose_name='Sức chứa')),
            ],
            options={
                'verbose_name': 'Phòng chiếu',
                'verbose_name_plural': 'Phòng chiếu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BaseUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông tin người dùng',
                'verbose_name_plural': 'Thông tin người dùng',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã ghế')),
                ('seat_number', models.IntegerField(verbose_name='Số ghế')),
                ('is_available', models.BooleanField(choices=[(True, 'Còn trống'), (False, 'Đã đặt')], default=True, verbose_name='Trạng thái')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_movie_ticket_app.room')),
            ],
            options={
                'verbose_name': 'Ghế',
                'verbose_name_plural': 'Ghế',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã vé')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Giá vé')),
                ('type', models.CharField(choices=[('Adult', 'Người lớn'), ('Child', 'Trẻ em')], max_length=100, verbose_name='Loại vé')),
                ('date_time', models.DateTimeField(verbose_name='Ngày giờ chiếu')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_movie_ticket_app.movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_movie_ticket_app.room', verbose_name='Phòng chiếu')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_movie_ticket_app.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đặt')),
            ],
            options={
                'verbose_name': 'Vé',
                'verbose_name_plural': 'Vé',
                'ordering': ['id'],
            },
        ),
    ]
